version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "AirControl/LevelSelect-src"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "DarkYears/Modding-src"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "NightmareSimulator/LevelSelect-src"
    schedule:
      interval: "daily"
