name: Build Air Control Level Select

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5

    - name: Restore with .NET Core
      run: cd AirControl/LevelSelect-src && dotnet restore *.sln

    - name: Build using .NET Core
      run: cd AirControl/LevelSelect-src && dotnet build *.sln --configuration Release --no-restore

    - name: Upload build as artifact
      uses: actions/upload-artifact@v4
      with:
        name: AirControlLevelSelect
        path: AirControl/LevelSelect-src/bin/Release/net452
