name: Build Audio CD for Big Rigs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install p7zip-full

        pip install av numpy
        curl -o build_cd.py https://gist.githubusercontent.com/spicyjpeg/97c450320796fc0cb00c2a1490fad98d/raw/76b2bf1589ad6c463a60633160d8d3ca4436dcbd/build_audio_cd.py
        sed -i 's/av.AudioResampler("flt", 2, 44100)/av.AudioResampler("flt", "stereo", 44100)/' build_cd.py

        # Mirror of the Abandonware France zip, on a website I actually paid for,
        # with a 100 MB file limit 
        curl --retry 3 --fail -o Big_Rigs.7z.001 https://files.gamebanana.com/bitpit/brotrrrrrr7z.001
        curl --retry 3 --fail -o Big_Rigs.7z.002 https://files.gamebanana.com/bitpit/brotrrrrrr7z.002
        curl --retry 3 --fail -o Big_Rigs.7z.003 https://files.gamebanana.com/bitpit/brotrrrrrr7z.003
        curl --retry 3 --fail -o Big_Rigs.7z.004 https://files.gamebanana.com/bitpit/brotrrrrrr7z.004

        7z x Big_Rigs.7z.001
        7z x "Big Rigs.iso"

        mkdir output
        python3 build_cd.py output/Big_Rigs_Audio.bin Music/Track2.wav Music/Track*

    - name: Upload generated CD as artifact
      uses: actions/upload-artifact@v4
      with:
        name: BigRigsAudio
        path: output
