name: Build Dark Years Mod

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4

    - name: Restore with .NET Core
      run: cd DarkYears/Modding-src && dotnet restore *.sln

    - name: Build using .NET Core
      run: cd DarkYears/Modding-src && dotnet build *.sln --configuration Release --no-restore

    - name: Upload build as artifact
      uses: actions/upload-artifact@v4
      with:
        name: DarkYearsMod
        path: DarkYears/Modding-src/bin/Release/net452
