name: Build and package Team 6 Network

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build and Prepare Package
      run: |
        cd Team6/NetworkPlay-src
        javac ovh/maddie480/*.java
        cd ../..
        mkdir -pv dist/classes/ovh/maddie480
        mv -v Team6/NetworkPlay-src/ovh/maddie480/*.class dist/classes/ovh/maddie480/
        mv -v Team6/NetworkPlay-src/*.bat dist/
        curl -o java.zip https://download.java.net/openjdk/jdk8u43/ri/openjdk-8u43-windows-i586.zip
        unzip java.zip
        mv -v java-se-8u43-ri/jre dist/

    - name: Upload build as artifact
      uses: actions/upload-artifact@v3
      with:
        name: Team6Network
        path: dist
