name: Build and package Team 6 Network

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Check for tabs
      run: |
        find "(" -name "*.java" -or -name "*.yml" -or -name "*.md" -or -name "*.bat" ")" -exec grep -Pl "\t" {} \; > matches.txt
        grep "" matches.txt && exit 1 || echo "No tab found!"

    - name: Check for CRLF
      run: |
        find "(" -name "*.java" -or -name "*.yml" -or -name "*.md" -or -name "*.bat" ")" -exec grep -Plz "\r\n" {} \; > matches.txt
        grep "" matches.txt && exit 1 || echo "No CRLF found!"

    - name: Check for trailing spaces
      run: |
        find "(" -name "*.java" -or -name "*.yml" -or -name "*.md" -or -name "*.bat" ")" -exec grep -Pl " $" {} \; > matches.txt
        grep "" matches.txt && exit 1 || echo "No trailing space found!"

    - name: Build and Prepare Package
      run: |
        cd Team6/NetworkPlay-src
        javac ovh/maddie480/*.java
        cd ../..
        mkdir -pv dist/classes/ovh/maddie480
        mv -v Team6/NetworkPlay-src/ovh/maddie480/*.class dist/classes/ovh/maddie480/
        mv -v Team6/NetworkPlay-src/*.bat dist/
        curl -o java.zip https://download.java.net/openjdk/jdk8u43/ri/openjdk-8u43-windows-i586.zip
        tar xzvf java.zip
        mv -v jre dist/

    - name: Upload build as artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: target
        path: dist
